[package]
name = "scratch"
version = "0.1.0"
authors = ["m.nimalan <m.nimalan@thoughtworks.com>"]
edition = "2018"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
